import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { ThemeProvider } from "@/components/theme-provider"
import './globals.css'
import Navbar from '@/components/navbar/navbar'
import NextAuthSessionProvider from '@/providers/session-provider'
import ModalProvider from '@/providers/modal-provider'
import ToastProvider from '@/providers/toast-provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
            attribute="class"
            defaultTheme=""
            enableSystem
            disableTransitionOnChange
          >
          <NextAuthSessionProvider>
            <ModalProvider />
            <ToastProvider />
            <Navbar />
            {children}
          </NextAuthSessionProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
