on: 
  pull_request:
    branches:
      ['*']
  push: 
    branches: 
      ['*']

jobs: 
  continuous-integration: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: Using Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: 20.x
        
      - name: Set up environment variables
        run: |
          cd courseplatform-back
          echo "APP_KEY=${{ secrets.APP_KEY }}" > .env
          echo "DB_CONNECTION=${{ secrets.DB_CONNECTION }}" >> .env
          echo "DRIVE_DISK=${{ secrets.DRIVE_DISK }}" >> .env
          echo "HOST=${{ secrets.HOST }}" >> .env
          echo "PG_DB_NAME=${{ secrets.PG_DB_NAME }}" >> .env
          echo "PG_HOST=${{ secrets.PG_HOST }}" >> .env
          echo "PG_PASSWORD=${{ secrets.PG_PASSWORD }}" >> .env
          echo "PG_PORT=${{ secrets.PG_PORT }}" >> .env
          echo "PG_USER=${{ secrets.PG_USER }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "SESSION_DRIVER=${{ secrets.SESSION_DRIVER }}" >> .env

      - name: Debug environment variables
        run: cat courseplatform-back/.env

      - name: run install, build and test
        run: |
          cd courseplatform-back
          npm install
          npm run build
          npm run test