name: Continuous Integration

on: 
  pull_request:
    branches:
      ['*']
  push: 
    branches: 
      ['master']

jobs: 
  build: 
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        node-version: ['20.x']
    environment: test
    
    steps:
      - uses: actions/checkout@v3
      - run: git fetch --prune --unshallow
        
      - name: Using Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with: 
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          cd courseplatform-back
          yarn --frozen-lockfile

      - name: Run all tests
        run: |
          cd courseplatform-back
          yarn test

      - name: Run build
        run: |
          cd courseplatform-back
          yarn build --ignore-ts-errors
